#!/usr/bin/env bash

source lib

function day() {
    local -i e=1

    local d="day${1}"
    if [ -e $d/solve.sh ]; then
        printf "#. Day %-2d" $i
        printf " 0%080x\n" 0|tr 0 '#'

        source ${d}/solve.sh

        cd $d; {
            local INPUT=$(pwd)/input.txt
            [ ! -e "/tmp/${d}.txt" ] || INPUT="/tmp/${d}.txt"

            local -a functions=(
                $(declare -F|awk "\$3~/adventofcode:d$1p$2/{print\$3}")
            )

            for fn in "${functions[@]}"; do
                timer ${fn}
            done
        }; cd ..

        e=0
    fi

    return $e
}

case $# in
    0) for i in {1..25}; do day $i; done ;;
    1) day $1 ;;
    2) day $1 $2 ;;
esac
