#!/usr/bin/env bash

source lib

function day() {
    local d="day${1}"
    local INPUT=${d}/input.txt
    [ ! -e "/tmp/${d}.txt" ] || INPUT="/tmp/${d}.txt"

    source ${d}/solve.sh

    local -a functions=(
        $(declare -F|awk "\$3~/adventofcode:d$1p/{print\$3}")
    )

    for fn in "${functions[@]}"; do
        timer ${fn}
    done
}

declare -a days=( {1..25} )
[ $# -eq 0 ] || days=( $@ )

for i in ${days[@]}; do
    if [ -e day$i/solve.sh ]; then
        printf "#. Day %-2d" $i
        printf " 0%080x\n" 0|tr 0 '#'
        day $i
    fi
done
